import {
  VITE_BASE_BOARDS_API_URL,
  VITE_BASE_LISTS_API_URL,
  VITE_BASE_CARDS_API_URL,
  VITE_BASE_CHECKLISTS_API_URL,
  VITE_BASE_CHECKLIST_ITEM_API_URL,
  VITE_API_KEY,
  VITE_API_TOKEN,
} from "@env";

export const config = {
  baseBoardsUrl: VITE_BASE_BOARDS_API_URL,
  baseListsUrl: VITE_BASE_LISTS_API_URL,
  baseCardsUrl: VITE_BASE_CARDS_API_URL,
  baseChecklistsUrl: VITE_BASE_CHECKLISTS_API_URL,
  baseChecklistItemUrl: VITE_BASE_CHECKLIST_ITEM_API_URL,
  key: VITE_API_KEY,
  token: VITE_API_TOKEN,
};
